spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/demo
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    encoding: UTF-8
    basename: messages
  mvc:
    log-resolved-exception: false